import { useEffect, useState } from "react";
import DashboardLayout from "../../components/layout/DashboardLayout";
import {
    getMyLinks,
    searchLinks,
    getFavoriteLinks,
    getPinnedLinks,
    getExpiredLinks,
    getActiveLinks,
    getCustomAliasLinks,
    getAutoGeneratedLinks,
} from "../../services/linkService";
import api from "../../api/axios";
import toast from "react-hot-toast";
import CreateLinkModal from "../../components/links/CreateLinkModal";
import LinkCard from "../../components/links/LinkCard";
import DeleteLinkModal from "../../components/links/DeleteLinkModal";
import AssignTagModal from "../../components/tags/AssignTagModal";
import AssignCategoryModal from "../../components/categories/AssignCategoryModal";
import AssignCollectionModal from "../../components/collections/AssignCollectionModal";
import PasswordModal from "../../components/links/PasswordModal";
import {
    Plus,
    Search,
    SlidersHorizontal,
    Grid3X3,
    List,
    Trash2,
    Loader2,
    Link2,
    ChevronLeft,
    ChevronRight,
    CheckSquare,
    Square,
    X,
} from "lucide-react";

export default function MyLinks() {
    const [links, setLinks] = useState([]);
    const [loading, setLoading] = useState(true);
    const [openModal, setOpenModal] = useState(false);
    const [deleteOpen, setDeleteOpen] = useState(false);
    const [selectedId, setSelectedId] = useState(null);
    const [editingLink, setEditingLink] = useState(null);
    const [search, setSearch] = useState("");
    const [filter, setFilter] = useState("all");
    const [page, setPage] = useState(0);
    const [totalPages, setTotalPages] = useState(0);
    const [assignOpen, setAssignOpen] = useState(false);
    const [selectedLinkId, setSelectedLinkId] = useState(null);
    const [assignCategoryOpen, setAssignCategoryOpen] = useState(false);
    const [assignCollectionOpen, setAssignCollectionOpen] = useState(false);
    const [selectedCollectionLinkId, setSelectedCollectionLinkId] = useState(null);
    const [passwordModalOpen, setPasswordModalOpen] = useState(false);
    const [passwordLinkId, setPasswordLinkId] = useState(null);
    const [viewMode, setViewMode] = useState("list");
    const [selectedLinks, setSelectedLinks] = useState([]);
    const [bulkLoading, setBulkLoading] = useState(false);
    const [showFilters, setShowFilters] = useState(false);

    useEffect(() => {
        if (search.trim() !== "") {
            handleSearch(search, page);
        } else if (filter !== "all") {
            handleFilter(filter, page);
        } else {
            fetchLinks(page);
        }
    }, [page]);

    const openDeleteModal = (id) => {
        setSelectedId(id);
        setDeleteOpen(true);
    };

    const openEditModal = (link) => {
        setEditingLink(link);
        setOpenModal(true);
    };

    const openPasswordModal = (id) => {
        setPasswordLinkId(id);
        setPasswordModalOpen(true);
    };

    const fetchLinks = async (pageNumber = 0) => {
        setLoading(true);
        try {
            const response = await getMyLinks(pageNumber);
            setLinks(response.content);
            setPage(response.number);
            setTotalPages(response.totalPages);
        } catch (error) {
            console.error(error);
        } finally {
            setLoading(false);
        }
    };

    const handleSearch = async (keyword, pageNumber = 0) => {
        setSearch(keyword);
        if (keyword.trim() === "") {
            fetchLinks(pageNumber);
            return;
        }
        try {
            const response = await searchLinks(keyword, pageNumber);
            setLinks(response.content);
            setPage(response.number);
            setTotalPages(response.totalPages);
        } catch (error) {
            console.error(error);
        }
    };

    const handleFilter = async (value, pageNumber = 0) => {
        setFilter(value);
        try {
            let response;
            switch (value) {
                case "favorites":
                    response = await getFavoriteLinks(pageNumber);
                    break;
                case "pinned":
                    response = await getPinnedLinks(pageNumber);
                    break;
                case "expired":
                    response = await getExpiredLinks(pageNumber);
                    break;
                case "active":
                    response = await getActiveLinks(pageNumber);
                    break;
                case "custom":
                    response = await getCustomAliasLinks(pageNumber);
                    break;
                case "auto":
                    response = await getAutoGeneratedLinks(pageNumber);
                    break;
                default:
                    fetchLinks(pageNumber);
                    return;
            }
            setLinks(response.content);
            setPage(response.number);
            setTotalPages(response.totalPages);
        } catch (error) {
            console.error(error);
        }
    };

    // Bulk Selection
    const toggleSelectAll = () => {
        if (selectedLinks.length === links.length) {
            setSelectedLinks([]);
        } else {
            setSelectedLinks(links.map((l) => l.id));
        }
    };

    const toggleSelect = (id) => {
        setSelectedLinks((prev) =>
            prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]
        );
    };

    const handleBulkDelete = async () => {
        if (!window.confirm(`Delete ${selectedLinks.length} selected links?`)) return;
        setBulkLoading(true);
        try {
            await Promise.all(
                selectedLinks.map((id) => api.delete(`/api/links/${id}`))
            );
            setSelectedLinks([]);
            toast.success(`${selectedLinks.length} links deleted`);
            fetchLinks(page);
        } catch (error) {
            toast.error("Bulk delete failed");
        } finally {
            setBulkLoading(false);
        }
    };

    // Loading skeleton
    const SkeletonCard = () => (
        <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-5 animate-pulse">
            <div className="flex justify-between">
                <div className="space-y-3 flex-1">
                    <div className="h-5 bg-slate-200 dark:bg-slate-700 rounded w-1/3" />
                    <div className="h-4 bg-slate-200 dark:bg-slate-700 rounded w-2/3" />
                </div>
                <div className="flex gap-2">
                    <div className="w-8 h-8 bg-slate-200 dark:bg-slate-700 rounded-lg" />
                    <div className="w-8 h-8 bg-slate-200 dark:bg-slate-700 rounded-lg" />
                </div>
            </div>
            <div className="mt-4 h-4 bg-slate-200 dark:bg-slate-700 rounded w-full" />
            <div className="mt-6 flex gap-2">
                {[1, 2, 3, 4].map((i) => (
                    <div key={i} className="h-9 bg-slate-200 dark:bg-slate-700 rounded-xl w-20" />
                ))}
            </div>
        </div>
    );

    return (
        <DashboardLayout>
            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
                <div>
                    <h1 className="text-3xl font-bold text-slate-800 dark:text-white">My Links</h1>
                    <p className="text-slate-500 dark:text-slate-400">Manage all your shortened links</p>
                </div>
                <button
                    onClick={() => setOpenModal(true)}
                    className="btn-primary px-5 py-3 rounded-xl text-sm flex items-center gap-2"
                >
                    <Plus size={18} />
                    Create Link
                </button>
</div>

            {/* Content */}
            {loading ? (
                <div className={viewMode === "grid" ? "grid grid-cols-1 md:grid-cols-2 gap-5" : "space-y-4"}>
                    {[1, 2, 3, 4].map((i) => (
                        <SkeletonCard key={i} />
                    ))}
                </div>
            ) : links.length === 0 ? (
                <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-12 text-center">
                    <div className="w-16 h-16 rounded-2xl bg-slate-100 dark:bg-slate-700 flex items-center justify-center mx-auto mb-4">
                        <Link2 size={32} className="text-slate-400" />
                    </div>
                    <h2 className="text-xl font-bold text-slate-800 dark:text-white mb-2">
                        No Links Yet
                    </h2>
                    <p className="text-slate-500 dark:text-slate-400 mb-6">
                        Create your first shortened link to get started.
                    </p>
                    <button
                        onClick={() => setOpenModal(true)}
                        className="btn-primary px-6 py-3 rounded-xl text-sm"
                    >
                        <Plus size={18} />
                        Create Your First Link
                    </button>
                </div>
            ) : (
                <>
                    {/* Bulk Select All (header) */}
                    <div className="flex items-center gap-2 mb-3">
                        <button
                            onClick={toggleSelectAll}
                            className="flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600 transition"
                        >
                            {selectedLinks.length === links.length && links.length > 0 ? (
                                <CheckSquare size={16} className="text-blue-600" />
                            ) : (
                                <Square size={16} />
                            )}
                            {selectedLinks.length === links.length && links.length > 0
                                ? "Deselect All"
                                : "Select All"}
                        </button>
                        {selectedLinks.length > 0 && (
                            <span className="text-xs text-slate-400">
                                ({selectedLinks.length} selected)
                            </span>
                        )}
                    </div>

                    {/* Link Cards */}
                    <div
                        className={
                            viewMode === "grid"
                                ? "grid grid-cols-1 md:grid-cols-2 gap-5"
                                : "space-y-4"
                        }
                    >
                        {links.map((link) => (
                            <div key={link.id} className="relative group">
                                {/* Checkbox for bulk selection */}
                                <button
                                    onClick={() => toggleSelect(link.id)}
                                    className={`absolute -left-3 top-6 z-10 w-7 h-7 rounded-lg flex items-center justify-center transition-all opacity-0 group-hover:opacity-100 ${
                                        selectedLinks.includes(link.id)
                                            ? "opacity-100 bg-blue-600 text-white"
                                            : "bg-white dark:bg-slate-700 border border-slate-300 dark:border-slate-600 text-slate-400 hover:text-blue-600"
                                    }`}
                                >
                                    {selectedLinks.includes(link.id) ? (
                                        <CheckSquare size={16} />
                                    ) : (
                                        <Square size={16} />
                                    )}
                                </button>
                                <LinkCard
                                    link={link}
                                    onDelete={openDeleteModal}
                                    onEdit={openEditModal}
                                    onRefresh={() => fetchLinks(page)}
                                    onAssignTag={(id) => {
                                        setSelectedLinkId(id);
                                        setAssignOpen(true);
                                    }}
                                    onAssignCategory={(id) => {
                                        setSelectedLinkId(id);
                                        setAssignCategoryOpen(true);
                                    }}
                                    onAssignCollection={(id) => {
                                        setSelectedCollectionLinkId(id);
                                        setAssignCollectionOpen(true);
                                    }}
                                />
                            </div>
                        ))}
                    </div>

                    {/* Pagination */}
                    {totalPages > 1 && (
                        <div className="flex items-center justify-center gap-4 mt-8">
                            <button
                                disabled={page === 0}
                                onClick={() => setPage(page - 1)}
                                className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700 disabled:opacity-40 disabled:cursor-not-allowed transition"
                            >
                                <ChevronLeft size={16} />
                                Previous
                            </button>

                            <div className="flex items-center gap-1.5">
                                {Array.from({ length: Math.min(totalPages, 5) }, (_, i) => {
                                    const pageNum = i + 1;
                                    return (
                                        <button
                                            key={pageNum}
                                            onClick={() => setPage(pageNum - 1)}
                                            className={`w-9 h-9 rounded-xl text-sm font-medium transition ${
                                                page === pageNum - 1
                                                    ? "bg-blue-600 text-white shadow-md"
                                                    : "text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-700"
                                            }`}
                                        >
                                            {pageNum}
                                        </button>
                                    );
                                })}
                            </div>

                            <button
                                disabled={page + 1 >= totalPages}
                                onClick={() => setPage(page + 1)}
                                className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 text-sm font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-700 disabled:opacity-40 disabled:cursor-not-allowed transition"
                            >
                                Next
                                <ChevronRight size={16} />
                            </button>
                        </div>
                    )}
                </>
            )}

            {/* Modals */}
            <CreateLinkModal
                isOpen={openModal}
                onClose={() => {
                    setOpenModal(false);
                    setEditingLink(null);
                }}
                onSuccess={fetchLinks}
                editLink={editingLink}
            />
            <DeleteLinkModal
                open={deleteOpen}
                linkId={selectedId}
                onClose={() => setDeleteOpen(false)}
                onSuccess={fetchLinks}
            />
            <AssignTagModal
                open={assignOpen}
                onClose={() => setAssignOpen(false)}
                linkId={selectedLinkId}
                onSuccess={() => fetchLinks(page)}
            />
            <AssignCategoryModal
                isOpen={assignCategoryOpen}
                onClose={() => setAssignCategoryOpen(false)}
                linkId={selectedLinkId}
                onSuccess={() => fetchLinks(page)}
            />
            <AssignCollectionModal
                isOpen={assignCollectionOpen}
                onClose={() => setAssignCollectionOpen(false)}
                linkId={selectedCollectionLinkId}
                onSuccess={() => fetchLinks(page)}
            />
            <PasswordModal
                isOpen={passwordModalOpen}
                onClose={() => setPasswordModalOpen(false)}
                linkId={passwordLinkId}
                onSuccess={() => fetchLinks(page)}
            />
        </DashboardLayout>
    );
}

