import api from "../api/axios";

export const getMyLinks = async (page = 0) => {

    const response = await api.get(
        `/api/links?page=${page}&size=10`
    );

    return response.data;

};

export const createLink = async (data) => {
    const response = await api.post("/api/links", data);
    return response.data;
};

export const deleteLink = async (id) => {
    await api.delete(`/api/links/${id}`);
};

export const updateLink = async (id, data) => {
    const response = await api.put(`/api/links/${id}`, data);
    return response.data;
};

export const searchLinks = async (keyword, page = 0) => {
    const response = await api.get(`/api/links/search?page=${page}&size=10`, {
        params: { keyword }
    });
    return response.data;
};

export const getFavoriteLinks = async (page = 0) => {
    const response = await api.get(`/api/links/favorites?page=${page}&size=10`);
    return response.data;
};

export const getPinnedLinks = async (page = 0) => {
    const response = await api.get(`/api/links/pinned?page=${page}&size=10`);
    return response.data;
};

export const getExpiredLinks = async (page = 0) => {
    const response = await api.get(`/api/links/filter/expired?page=${page}&size=10`);
    return response.data;
};

export const getActiveLinks = async (page = 0) => {
    const response = await api.get(`/api/links/filter/non-expired?page=${page}&size=10`);
    return response.data;
};

export const getCustomAliasLinks = async (page = 0) => {
    const response = await api.get(`/api/links/filter/custom-alias?page=${page}&size=10`);
    return response.data;
};

export const getAutoGeneratedLinks = async (page = 0) => {
    const response = await api.get(`/api/links/filter/auto-generated?page=${page}&size=10`);
    return response.data;
};

export const favoriteLink = async (id) => {
    await api.put(`/api/links/${id}/favorite`);
};

export const unfavoriteLink = async (id) => {
    await api.put(`/api/links/${id}/unfavorite`);
};

export const pinLink = async (id) => {
    await api.put(`/api/links/${id}/pin`);
};

export const unpinLink = async (id) => {
    await api.delete(`/api/links/${id}/pin`);
};
